apiVersion: v1
kind: Namespace
metadata:
  name: ordis-e2e
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-repair
  namespace: ordis-e2e
  annotations:
    ordis.ai/repair-image: busybox:latest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ordis-e2e-image-repair
  template:
    metadata:
      labels:
        app: ordis-e2e-image-repair
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2
      containers:
      - name: web
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "exec sleep 3600"]
